### ISSUE TITLE
Songtekst lyric's

### ISSUE THREAD

**Issue by nextDNSconfig** [SpotCompiled/SpotilifeC#11]
ADD this feature

**Comment by yodaluca23** [comment]
I intend to leave [SpotilifeC](https://github.com/SpotCompiled/SpotilifeC) with solely Spotilife, if you want lyrics and other QOL features, take a look at [SpotC++](https://github.com/SpotCompiled/SpotC-Plus-Plus), which in addition to Spotilife, also has Sposify, which has the option to have lyrics, always show...
