### ISSUE TITLE
spotify version upgrade possibility

### ISSUE THREAD

**Issue by bachig26** [SpotCompiled/SpotilifeC#13]
Hi, I just found this repo where the Spotify is updated to version 8.8.12 with Spotilife and don't about the possibility with Sposify.

can you have look at it (https://github.com/purp0s3/Tweaked-iOS-Apps#spotify) and for the possibility in next/upcoming builds in SpotCompilied.

**Comment by verbes4** [comment]
+1 for this

**Comment by yodaluca23** [comment]
You can switch to [SpotveeC](https://github.com/SpotCompiled/SpotveeC), for more updated app versions, Spotilife is kind of dead, I doubt Julioverne will ever update it.
