### ISSUE TITLE
Difference with SpotC++?

### ISSUE THREAD

**Issue by aaronliu0130** [SpotCompiled/SpotilifeC#25]
Could you list which specific features SpotC++ has over SpotilifeC, assuming it does? The two have almost the exact same description. Thanks!

**Comment by yodaluca23** [comment]
> Could you list which specific features SpotC++ has over SpotilifeC, assuming it does? The two have almost the exact same description. Thanks!

SpotC++ has (in addition to Spotilife) Sposify, which you can see the features of [here](https://repo.dynastic.co/com.spos/).

**Comment by aaronliu0130** [comment]
Thanks for the quick response! Also, is only being able to log in with email a wontfix?

**Comment by yodaluca23** [comment]
> Also, is only being able to log in with email a wontfix?

Yes
