### ISSUE TITLE
"SpotC" could not be added to AltStore

### ISSUE THREAD

**Issue by Amazon90** [SpotCompiled/SpotilifeC#30]
![image](https://github.com/SpotCompiled/SpotilifeC/assets/72290820/d661ecce-75df-4379-a991-1f2d6da64c81)
![image](https://github.com/SpotCompiled/SpotilifeC/assets/72290820/712641f9-1a07-44c4-9cb9-b77b5c8c5360)

**Comment by yodaluca23** [comment]
What AltStore version are you on?

**Comment by Amazon90** [comment]
> What AltStore version are you on?

AltStore 1.7

**Comment by yodaluca23** [comment]
Upgrade to the latest beta using this source:

https://bit.ly/altstore-complete-min

**Comment by Amazon90** [comment]
> Upgrade to the latest beta using this source:
> 
> https://bit.ly/altstore-complete-min

Thank you. I'll try it.
