### ISSUE TITLE
Not supported by latest altStore version

### ISSUE THREAD

**Issue by deigo-lps** [SpotCompiled/SpotilifeC#36]
I am using AltStore 1.7 with AltServer 1.6.1

![screenshot](https://github.com/SpotCompiled/SpotilifeC/assets/81399211/8ed313f4-39a5-4f0a-badf-c32095f16ed6)

**Comment by An0n-00** [comment]
this should be resolved now. (if you have the latest altstore downloaded). 

it worked for me.
