### ISSUE TITLE
Premium not working

### ISSUE THREAD

**Issue by mrafieefard** [SpotCompiled/SpotilifeC#39]
Hello I sign app with Signulous but Its working like normal spotify![image](https://github.com/SpotCompiled/SpotilifeC/assets/54307278/8e723832-2dd8-47fa-abce-76c96fcfa661)

![image](https://github.com/SpotCompiled/SpotilifeC/assets/54307278/cc9314fc-6965-47f4-aa93-c18ac923373d)

![image](https://github.com/SpotCompiled/SpotilifeC/assets/54307278/df6dc4bc-7181-4b12-8841-9740219badcc)

Did I do something wrong?

**Comment by yodaluca23** [comment]
If it's your first time using it, go into Spotilife settings, and click apply, force close it from the app switcher, and then reopen the app.

**Comment by mrafieefard** [comment]
Yeah i'm sorry I didn't check the dialog that showed me in first
