### ISSUE TITLE
New interface not there!

### ISSUE THREAD

**Issue by Nateay0** [SpotCompiled/SpotilifeC#8]
![image](https://user-images.githubusercontent.com/92893096/217083719-0b26d931-a116-4396-ac0f-9ca5a7033921.png)

**Comment by yodaluca23** [comment]
Wdym by "new interface"?

**Comment by Nateay0** [comment]
> Wdym by "new interface"?

Like the newest ui

**Comment by yodaluca23** [comment]
> > Wdym by "new interface"?
> 
> Like the newest ui 
> At the bottom

I mean based on the pictures in the App Store, it looks the same to me… could you send a screenshot?

But if it was like, new in like the last seven months then it's probably because the the Spotify version that is compatible with Spotilife is not the latest...

**Comment by Nateay0** [comment]
> > > Wdym by "new interface"?
> > 
> > Like the newest ui 
> > At the bottom
> 
> I mean based on the pictures in the App Store, it looks the same to me… could you send a screenshot?
> 
> But if it was like, new in like the last seven months then it's probably because the the Spotify version that is compatible with Spotilife is not the latest...

It's supposed to be like this 
![image](https://user-images.githubusercontent.com/92893096/217101210-8608e99b-8d99-4fb6-950e-cdb6e0e4c757.png)

**Comment by yodaluca23** [comment]
> > I mean based on the pictures in the App Store, it looks the same to me… could you send a screenshot?
> > 
> > But if it was like, new in like the last seven months then it's probably because the the Spotify version that is compatible with Spotilife is not the latest...
> 
> It's supposed to be like this 
> ![image](https://user-images.githubusercontent.com/92893096/217101210-8608e99b-8d99-4fb6-950e-cdb6e0e4c757.png)

Oh, do you mean the darker color scheme and semi-transparency?

**Comment by Nateay0** [comment]
> > > I mean based on the pictures in the App Store, it looks the same to me… could you send a screenshot?
> > > But if it was like, new in like the last seven months then it's probably because the the Spotify version that is compatible with Spotilife is not the latest...
> > 
> > 
> > It's supposed to be like this
> > ![image](https://user-images.githubusercontent.com/92893096/217101210-8608e99b-8d99-4fb6-950e-cdb6e0e4c757.png)
> 
> Oh, do you mean the darker color scheme and semi-transparency?

Yes that darker color scheme and semi-transparency.

**Comment by yodaluca23** [comment]
> > Oh, do you mean the darker color scheme and semi-transparency?
> 
> Yes that darker color scheme and semi-transparency.

That must be a feature in later versions, I am constantly trying to find later versions that work, but for now, I'm going to close this, since theirs is no way to fix this with the current version...

But keep on the lookout for a new version!

**Comment by Nateay0** [comment]
Alright ty
